# Generated by Django 4.0.5 on 2022-06-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_colour_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purity',
            field=models.CharField(blank=True, choices=[('14', '14'), ('16', '16'), ('18', '18'), ('20', '20')], max_length=3, null=True),
        ),
    ]
