# Generated by Django 4.0.5 on 2022-06-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_purity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purity',
        ),
        migrations.CreateModel(
            name='GoldFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(blank=True, choices=[('rose', 'rose'), ('yellow', 'yellow'), ('white', 'white')], max_length=7, null=True)),
                ('purity', models.CharField(blank=True, choices=[('14', '14'), ('16', '16'), ('18', '18'), ('20', '20')], max_length=3, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
