# Generated by Django 4.0.5 on 2022-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metal',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platinum')], max_length=9, null=True),
        ),
    ]
