# Generated by Django 4.0.5 on 2022-06-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metal',
            field=models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platinum')], default='Silver', max_length=9, null=True),
        ),
    ]
