# Generated by Django 4.0.5 on 2022-09-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sustainable_ssentials_image', models.ImageField(upload_to='product')),
                ('future_image', models.ImageField(upload_to='product')),
                ('recycle_image', models.ImageField(upload_to='product')),
                ('low_carbon_image', models.ImageField(upload_to='product')),
                ('necklace_image', models.ImageField(upload_to='product')),
                ('earring_image', models.ImageField(upload_to='product')),
                ('ring_image', models.ImageField(upload_to='product')),
                ('bracelete_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='product')),
                ('lepos_london_user_image', models.ImageField(upload_to='product')),
                ('index_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
