# Generated by Django 4.0.5 on 2022-09-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_index_images_sliderimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index_images',
            new_name='Index_image',
        ),
    ]
