# Generated by Django 4.0.5 on 2022-09-20 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_index_images_index_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimages',
            name='index_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.index_image'),
        ),
    ]
