# Generated by Django 4.0.5 on 2022-09-20 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_sliderimages_index_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimages',
            name='lepos_london_user_image',
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lepos_london_user_image', models.ImageField(upload_to='product')),
                ('index_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.index_image')),
            ],
        ),
    ]
