# Generated by Django 4.0.5 on 2022-09-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_sliderimages_lepos_london_user_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSiteUSer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='userimages',
            name='index_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.websiteuser'),
        ),
    ]
