# Generated by Django 4.0.5 on 2022-09-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_websiteuser_alter_userimages_index_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeposLondonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.DeleteModel(
            name='UserImages',
        ),
        migrations.DeleteModel(
            name='WebSiteUSer',
        ),
    ]
