# Generated by Django 4.0.5 on 2022-09-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_leposlondonuser_delete_userimages_delete_websiteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_image',
            name='recycle_image',
        ),
    ]
