# Generated by Django 4.0.5 on 2022-09-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_price_product_metal_14_pice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index_image',
            old_name='bracelete_image',
            new_name='bracelet_image',
        ),
    ]
