# Generated by Django 4.0.5 on 2022-09-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_rename_bracelete_image_index_image_bracelet_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='metal_14_pice',
            new_name='metal_14_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='metal_16_pice',
            new_name='metal_16_price',
        ),
    ]
