# Generated by Django 4.0.5 on 2022-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_rename_metal_14_pice_product_metal_14_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('title3', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
            ],
        ),
    ]
