# Generated by Django 4.0.5 on 2022-09-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='text2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='text3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
