# Generated by Django 4.0.5 on 2022-09-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_quote_text2_quote_text3'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_image',
            name='bespoke_video',
            field=models.FileField(blank=True, null=True, upload_to='product'),
        ),
    ]
