# Generated by Django 4.0.5 on 2022-09-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_index_image_bespoke_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeJewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('bespoke_video', models.FileField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='FutureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('text2', models.CharField(max_length=255)),
                ('text3', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image1', models.ImageField(upload_to='product')),
                ('name1', models.CharField(max_length=255)),
                ('image2', models.ImageField(upload_to='product')),
                ('name2', models.CharField(max_length=255)),
                ('image3', models.ImageField(upload_to='product')),
                ('name3', models.CharField(max_length=255)),
                ('image4', models.ImageField(upload_to='product')),
                ('name4', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='LeposLondonUser',
            new_name='SustainableEssentials',
        ),
        migrations.RenameField(
            model_name='sustainableessentials',
            old_name='image',
            new_name='sustainable_essentials_image',
        ),
        migrations.RenameField(
            model_name='sustainableessentials',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='index_image',
            name='bespoke_video',
        ),
        migrations.RemoveField(
            model_name='index_image',
            name='future_image',
        ),
        migrations.RemoveField(
            model_name='index_image',
            name='low_carbon_image',
        ),
        migrations.RemoveField(
            model_name='index_image',
            name='sustainable_ssentials_image',
        ),
    ]
