# Generated by Django 4.0.5 on 2022-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_bespokejewellery_futuresection_websiteuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespokejewellery',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
