# Generated by Django 4.0.5 on 2022-09-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_delete_sustainableessentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bespokejewellery',
            name='text',
        ),
        migrations.AddField(
            model_name='bespokejewellery',
            name='text1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bespokejewellery',
            name='text2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bespokejewellery',
            name='text3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
