# Generated by Django 4.0.5 on 2022-09-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_bespokejewellery_text_bespokejewellery_text1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainableEssentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='')),
            ],
        ),
    ]
