# Generated by Django 4.0.5 on 2022-10-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_sustainableessentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='metal',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='metal_14_price',
            new_name='material_14_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='metal_16_price',
            new_name='material_16_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='metal_18_price',
            new_name='material_18_price',
        ),
    ]
