# Generated by Django 4.0.5 on 2022-10-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_rename_metal_product_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSustainableEssentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='')),
            ],
        ),
    ]
