# Generated by Django 4.0.5 on 2022-10-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_product_is_size_productsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='material_16_price',
            new_name='material_10_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('10', '10'), ('14', '14'), ('18', '18')], default='14', max_length=9, null=True),
        ),
    ]
