# Generated by Django 4.0.5 on 2022-10-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_rename_material_16_price_product_material_10_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSliderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=50)),
                ('text2', models.CharField(max_length=50)),
            ],
        ),
    ]
