# Generated by Django 4.0.5 on 2022-06-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='strength',
        ),
    ]
