# Generated by Django 4.0.5 on 2022-06-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='package',
        ),
    ]
