# Generated by Django 4.0.5 on 2022-09-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='metal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
