# Generated by Django 4.0.5 on 2022-09-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_metal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
