# Generated by Django 4.0.5 on 2022-10-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='metal',
            new_name='material',
        ),
    ]
