# Generated by Django 4.0.5 on 2022-10-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='terms_conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=50)),
                ('text1', models.CharField(max_length=50)),
                ('text2', models.CharField(max_length=50)),
                ('text3', models.CharField(max_length=50)),
                ('text4', models.CharField(max_length=50)),
                ('text5', models.CharField(max_length=50)),
            ],
        ),
    ]
